# -*- coding: utf-8 -*-
"""funnel analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkgBfuHBKOKMB69ULSK8K5apE0tp8u5j
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("default")
pd.set_option("display.max_columns", None)



import pandas as pd
users = pd.read_csv("users.csv")
events = pd.read_csv("funnel_events.csv")
subscriptions = pd.read_csv("subscriptions.csv")

users.head()
users.info()
users.describe(include="all")

events.head()
subscriptions.head()

print("Users Missing Values:\n", users.isnull().sum())
print("\nEvents Missing Values:\n", events.isnull().sum())
print("\nSubscriptions Missing Values:\n", subscriptions.isnull().sum())

stage_counts = events["funnel_stage"].value_counts()

plt.figure()
stage_counts.plot(kind="bar")
plt.title("Users at Each Funnel Stage")
plt.xlabel("Funnel Stage")
plt.ylabel("Number of Users")
plt.xticks(rotation=45)
plt.show()

signup_users = events[events["funnel_stage"] == "Signup"]["user_id"].nunique()
paid_users = events[events["funnel_stage"] == "Subscription Purchased"]["user_id"].nunique()

conversion_rate = (paid_users / signup_users) * 100

print(f"Signup to Paid Conversion Rate: {conversion_rate:.2f}%")

funnel_order = [
    "Signup",
    "Email Verified",
    "Trial Started",
    "Feature Used",
    "Subscription Purchased",
    "Retained 30 Days"
]

stage_counts = (
    events.groupby("funnel_stage")["user_id"]
    .nunique()
    .reindex(funnel_order)
)

drop_off = stage_counts.pct_change() * -100
drop_off

merged = users.merge(events, on="user_id")

channel_conversion = (
    merged[merged["funnel_stage"].isin(["Signup", "Subscription Purchased"])]
    .groupby(["acquisition_channel", "funnel_stage"])["user_id"]
    .nunique()
    .unstack()
)

channel_conversion["conversion_rate_%"] = (
    channel_conversion["Subscription Purchased"] /
    channel_conversion["Signup"] * 100
)

channel_conversion.sort_values("conversion_rate_%", ascending=False)

ab_conversion = (
    merged[merged["funnel_stage"].isin(["Signup", "Subscription Purchased"])]
    .groupby(["experiment_group", "funnel_stage"])["user_id"]
    .nunique()
    .unstack()
)

ab_conversion["conversion_rate_%"] = (
    ab_conversion["Subscription Purchased"] /
    ab_conversion["Signup"] * 100
)

ab_conversion

total_revenue = subscriptions["monthly_price"].sum()
arpu = subscriptions["monthly_price"].mean()

print("Total Monthly Revenue:", total_revenue)
print("Average Revenue Per User (ARPU):", round(arpu, 2))

rev_channel = subscriptions.merge(users, on="user_id")

rev_analysis = (
    rev_channel.groupby("acquisition_channel")["monthly_price"]
    .mean()
    .sort_values(ascending=False)
)

rev_analysis

users["signup_month"] = pd.to_datetime(users["signup_date"]).dt.to_period("M")
events["event_month"] = pd.to_datetime(events["event_date"]).dt.to_period("M")

cohort = (
    users.merge(events, on="user_id")
    .groupby(["signup_month", "event_month"])["user_id"]
    .nunique()
    .unstack(fill_value=0)
)

cohort